name: publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List Directories for Debugging
      run: |
        Write-Host "Listing BuildScripts Directory:"
        Get-ChildItem "$Env:GITHUB_WORKSPACE\BuildScripts"
        Write-Host "Listing Root Directory:"
        Get-ChildItem $Env:GITHUB_WORKSPACE
      shell: pwsh

    - name: Check Version
      run: ${{ github.workspace }}\BuildScripts\VersionCheck.ps1
      shell: pwsh

    - name: Build and Publish
      if: success()
      run: ${{ github.workspace }}\BuildScripts\Publish.ps1

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WebWhack/bin/Release/*.json
        asset_name: releases.json
        asset_content_type: application/json

    - name: Upload NuGet Packages
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WebWhack/bin/Release/*.nupkg
        asset_name: package.nupkg
        asset_content_type: application/octet-stream

    - name: Upload Installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WebWhack/bin/Release/WebpWhack-win-Setup.exe
        asset_name: WebpWhack-win-Setup.exe
        asset_content_type: application/octet-stream

    - name: Upload Portable Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./WebWhack/bin/Release/WebpWhack-win-Portable.zip
        asset_name: WebpWhack-win-Portable.zip
        asset_content_type: application/zip
